# Generated by Django 5.0.6 on 2025-09-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('content', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'textbox',
            },
        ),
    ]
