# Generated by Django 5.0.6 on 2025-09-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbox',
            name='code',
            field=models.TextField(unique=True),
        ),
    ]
