# Generated by Django 5.2.5 on 2025-09-03 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(default=None, max_length=100, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, default=None, null=True)),
            ],
        ),
    ]
