# Generated by Django 5.2.5 on 2025-09-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anonymous',
            table='anonymous',
        ),
    ]
