# Generated by Django 5.0.6 on 2025-09-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0002_alter_anonymous_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymous',
            name='cordinates',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anonymous',
            name='isp',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='location',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
