# Generated by Django 5.0.6 on 2025-09-02 11:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=3)),
                ('message', models.TextField(max_length=2000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('qchat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='qchat.quickchat')),
            ],
        ),
    ]
