# Generated by Django 5.0.6 on 2025-09-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations',
            name='sender',
            field=models.CharField(max_length=10),
        ),
    ]
