# Generated by Django 5.2.5 on 2025-09-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conversations',
            table='qc_conversations',
        ),
        migrations.AlterModelTable(
            name='quickchat',
            table='qc_chat',
        ),
    ]
