# Generated by Django 5.0.6 on 2025-09-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qchat', '0002_alter_conversations_table_alter_quickchat_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickchat',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
