# Generated by Django 5.0.6 on 2025-09-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qchat', '0003_alter_quickchat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickchat',
            name='incorrect_pw_count',
            field=models.IntegerField(default=0),
        ),
    ]
