# Generated by Django 5.0.6 on 2025-12-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qchat', '0004_quickchat_incorrect_pw_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickchat',
            name='email',
            field=models.JSONField(max_length=200, null=True),
        ),
    ]
