# Generated by Django 5.0.6 on 2025-12-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qchat', '0005_quickchat_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickchat',
            old_name='email',
            new_name='emails',
        ),
    ]
