# Generated by Django 5.0.6 on 2025-12-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qchat', '0006_rename_email_quickchat_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickchat',
            name='last_email_time',
            field=models.DateTimeField(null=True),
        ),
    ]
