# Generated by Django 5.0.6 on 2025-12-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qchat', '0007_quickchat_last_email_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickchat',
            name='last_email_send_by',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
