# Generated by Django 5.0.6 on 2025-08-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatusers',
            old_name='penname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='chatusers',
            name='token',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatusers',
            name='token_created_on',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
