# Generated by Django 5.2.5 on 2025-08-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_penname_chatusers_name_chatusers_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatusers',
            name='token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chatusers',
            name='token_created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
