# Generated by Django 5.0.6 on 2025-09-02 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatusers_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickConversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conv_name', models.CharField(max_length=10)),
                ('conv_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('sender', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
    ]
