# Generated by Django 5.0.6 on 2025-09-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_quickconversations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickConversations',
        ),
    ]
